# Generated by Django 5.2.13 on 2026-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_dependencies_remove_team_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
