# Generated by Django 5.2.13 on 2026-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
