<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-04-23 17:15
=======
# Generated by Django 5.2.13 on 2026-04-23 17:55
>>>>>>> 56d03af (update all)

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
