# Generated by Django 5.2.13 on 2026-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_members_alter_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github_repo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
