# Generated by Django 6.0.4 on 2026-04-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_dependencies', to='teams.team'),
        ),
    ]
