# Generated by Django 6.0.4 on 2026-04-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_dependency_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='team',
        ),
    ]
