# Generated by Django 6.0.4 on 2026-04-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_dependency_team_alter_team_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependency',
            name='team',
        ),
    ]
