# Generated by Django 6.0.4 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='specialisation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
