# Generated by Django 5.2.13 on 2026-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_project_name', models.CharField(max_length=200)),
                ('jira_board_link', models.URLField(max_length=300)),
                ('repo_url', models.URLField(max_length=300, unique=True)),
                ('work_stream', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
