# Generated by Django 5.2.13 on 2026-04-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_is_draft'),
        ('teams', '0005_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
